# This file was generated by GoReleaser. DO NOT EDIT.
cask "pg_mini" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "a902404b297ed48cad2c43749c24ab69731bce0251001531e3fae0f3ee6782a2"
      url "https://github.com/fritzkeyzer/pg_mini/releases/download/v#{version}/pg_mini_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1d9cb46361a90d88e7ce3577b165a8f3782fc2609e31e306f382a7ce2aa7e665"
      url "https://github.com/fritzkeyzer/pg_mini/releases/download/v#{version}/pg_mini_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fc04de6ef88923094708a086200421dfdb4e9aeb909dc23c112234cecaba5c0b"
      url "https://github.com/fritzkeyzer/pg_mini/releases/download/v#{version}/pg_mini_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "93ddc3d301af9d5c9d461f828d27bbb33b4845a157b2dc34017adb3c69423958"
      url "https://github.com/fritzkeyzer/pg_mini/releases/download/v#{version}/pg_mini_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pg_mini"
  desc "Create consistent, partial backups of PostgreSQL databases"
  homepage "https://github.com/fritzkeyzer/pg_mini"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pg_mini"

  # No zap stanza required

end
