# This file was generated by GoReleaser. DO NOT EDIT.
cask "pg_mini" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "cfb92c0c342f29df1b3b29a99c506a46177280d5ecd4f1087a3df489ceb5d51d"
      url "https://github.com/fritzkeyzer/pg_mini/releases/download/v#{version}/pg_mini_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "972d0c6f38583656d8784e380dafd09897c3c46924d34d4c5b29336dab445fa9"
      url "https://github.com/fritzkeyzer/pg_mini/releases/download/v#{version}/pg_mini_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ce335a3481d82faf2c0756c2978d685b01f60ddef7e36c3603b3c39507e1bb0a"
      url "https://github.com/fritzkeyzer/pg_mini/releases/download/v#{version}/pg_mini_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f769b3660a1eb07e092264ea613926a7e174d0d262537dfee32077667e396fdd"
      url "https://github.com/fritzkeyzer/pg_mini/releases/download/v#{version}/pg_mini_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pg_mini"
  desc "Create consistent, partial backups of PostgreSQL databases"
  homepage "https://github.com/fritzkeyzer/pg_mini"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pg_mini"

  # No zap stanza required

end
